services:
  - type: web
    name: backend
    env: node
    rootDir: api/backend
    buildCommand: npm install
    startCommand: node app.cjs
    envVars:
      - key: MONGO_URI
        fromEnvironment: MONGO_URI

  - type: static
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: http://backend:5000/api/*
      - type: rewrite
        source: /*
        destination: /index.html
